In [15]:
import pandas as pd

In [16]:
# pip install scikit-learn==1.2.2 in needed packages

1.2.2

In [17]:
import pickle

# Load the model from the pickle file
with open('model.pkl', 'rb') as file:
    loaded_model = pickle.load(file)

In [18]:
csv_file_path = 'test.csv'

# Specify the row number you want to read (e.g., row 0 for the first row)
row_number_to_read = 0

# Read only one row into a DataFrame
df = pd.read_csv(csv_file_path)
# df = pd.read_csv(csv_file_path, nrows=row_number_to_read + 1)

In [19]:
df

,TransactionID,FraudIndicator,Category,TransactionAmount,AnomalyScore,Timestamp,MerchantID,Amount,CustomerID,Name,Age,Address,AccountBalance,LastLogin,SuspiciousFlag
0,1,0,Other,79.413607,0.686699,1/1/2022 0:00,2701,55.530334,1952,Customer 1952,50,Address 1952,2869.689912,8/9/2024,0
1,9,1,Retail,75.659944,0.010471,1/1/2022 8:00,2612,37.182412,1347,Customer 1347,20,Address 1347,8935.007146,12/13/2022,0
2,10,0,Other,67.931879,0.029376,1/1/2022 9:00,2638,17.245409,1574,Customer 1574,55,Address 1574,5541.197921,7/28/2023,0
3,140,0,Travel,44.405971,0.781759,1/6/2022 19:00,2180,36.941254,1574,Customer 1574,55,Address 1574,5541.197921,7/28/2023,0
4,11,0,Other,23.895623,0.083455,1/1/2022 10:00,2007,86.180948,1424,Customer 1424,37,Address 1424,4344.549864,2/28/2023,0
5,364,1,Travel,78.346754,0.830407,1/16/2022 3:00,2929,61.136532,1424,Customer 1424,37,Address 1424,4344.549864,2/28/2023,0
6,675,0,Other,76.002999,0.953422,1/29/2022 2:00,2511,34.240032,1424,Customer 1424,37,Address 1424,4344.549864,2/28/2023,0
7,701,0,Online,61.305263,0.198231,1/30/2022 4:00,2489,39.791263,1424,Customer 1424,37,Address 1424,4344.549864,2/28/2023,0
8,756,0,Retail,17.048150,0.284793,2/1/2022 11:00,2012,36.375603,1424,Customer 1424,37,Address 1424,4344.549864,2/28/2023,0
9,900,0,Retail,56.472761,0.031933,2/7/2022 11:00,2094,36.879275,1424,Customer 1424,37,Address 1424,4344.549864,2/28/2023,0
10,12,0,Food,17.797222,0.451735,1/1/2022 11:00,2746,95.554009,1302,Customer 1302,54,Address 1302,2670.113015,10/29/2022,0
11,13,0,Other,64.781658,0.444803,1/1/2022 12:00,2092,47.138514,1321,Customer 1321,47,Address 1321,2685.942365,11/17/2022,0
12,15,0,Other,35.450844,0.827926,1/1/2022 14:00,2849,99.832634,1321,Customer 1321,47,Address 1321,2685.942365,11/17/2022,0
13,14,0,Travel,43.691459,0.997340,1/1/2022 13:00,2892,98.804250,1700,Customer 1700,22,Address 1700,6735.159471,12/1/2023,0
14,16,0,Other,47.627375,0.455947,1/1/2022 15:00,2640,20.735039,1463,Customer 1463,46,Address 1463,1847.326392,4/8/2023,0
15,17,0,Other,83.800434,0.078617,1/1/2022 16:00,2858,44.545119,1962,Customer 1962,39,Address 1962,7989.117483,8/19/2024,0
16,18,0,Travel,67.019735,0.532820,1/1/2022 17:00,2479,27.054937,1854,Customer 1854,57,Address 1854,9960.172528,5/3/2024,0
17,823,0,Other,47.241461,0.565657,2/4/2022 6:00,2013,61.035508,1854,Customer 1854,57,Address 1854,9960.172528,5/3/2024,0
18,19,1,Food,79.679529,0.252012,1/1/2022 18:00,2470,13.615519,1651,Customer 1651,58,Address 1651,8326.149989,10/13/2023,0

In [20]:
columns_to_be_dropped = ['TransactionID','MerchantID','CustomerID','Name', 'Age', 'Address']
df = df.drop(columns_to_be_dropped, axis=1)

In [21]:
df['Timestamp1'] = pd.to_datetime(df['Timestamp'])
df['Hour'] = df['Timestamp1'].dt.hour
df['LastLogin'] = pd.to_datetime(df['LastLogin'])
df['gap'] = (df['Timestamp1'] - df['LastLogin']).dt.days.abs()

In [22]:
df = df.drop(['FraudIndicator','Timestamp','Timestamp1','LastLogin'],axis=1)

In [23]:
import pandas as pd

# Assuming 'df' is your DataFrame and 'Category' is the column to encode
all_categories = ['Online', 'Other', 'Travel', 'Food', 'Retail']  # List of all possible categories

for category in all_categories:
    new_column_name = f'Category_{category}'
    df[new_column_name] = (df['Category'] == category).astype(int)

# Drop the original 'Category' column
df.drop('Category', axis=1, inplace=True)

In [24]:
df

,TransactionAmount,AnomalyScore,Amount,AccountBalance,SuspiciousFlag,Hour,gap,Category_Online,Category_Other,Category_Travel,Category_Food,Category_Retail
0,79.413607,0.686699,55.530334,2869.689912,0,0,951,0,1,0,0,0
1,75.659944,0.010471,37.182412,8935.007146,0,8,346,0,0,0,0,1
2,67.931879,0.029376,17.245409,5541.197921,0,9,573,0,1,0,0,0
3,44.405971,0.781759,36.941254,5541.197921,0,19,568,0,0,1,0,0
4,23.895623,0.083455,86.180948,4344.549864,0,10,423,0,1,0,0,0
5,78.346754,0.830407,61.136532,4344.549864,0,3,408,0,0,1,0,0
6,76.002999,0.953422,34.240032,4344.549864,0,2,395,0,1,0,0,0
7,61.305263,0.198231,39.791263,4344.549864,0,4,394,1,0,0,0,0
8,17.048150,0.284793,36.375603,4344.549864,0,11,392,0,0,0,0,1
9,56.472761,0.031933,36.879275,4344.549864,0,11,386,0,0,0,0,1
10,17.797222,0.451735,95.554009,2670.113015,0,11,301,0,0,0,1,0
11,64.781658,0.444803,47.138514,2685.942365,0,12,320,0,1,0,0,0
12,35.450844,0.827926,99.832634,2685.942365,0,14,320,0,1,0,0,0
13,43.691459,0.997340,98.804250,6735.159471,0,13,699,0,0,1,0,0
14,47.627375,0.455947,20.735039,1847.326392,0,15,462,0,1,0,0,0
15,83.800434,0.078617,44.545119,7989.117483,0,16,961,0,1,0,0,0
16,67.019735,0.532820,27.054937,9960.172528,0,17,853,0,0,1,0,0
17,47.241461,0.565657,61.035508,9960.172528,0,6,819,0,1,0,0,0
18,79.679529,0.252012,13.615519,8326.149989,0,18,650,0,0,0,1,0

In [25]:
fix_order = ['TransactionAmount','AnomalyScore','Amount','AccountBalance','SuspiciousFlag','Hour','gap','Category_Food','Category_Online','Category_Other','Category_Retail','Category_Travel']

In [26]:
df = df.reindex(columns=fix_order)

In [27]:
predictions = loaded_model.predict(df)
predictions

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
      dtype=int64)

In [28]:
probabilities = loaded_model.predict_proba(df)

# Assuming '1' is the label for fraud
fraud_probabilities = probabilities[:, 1]

# You can set a threshold (e.g., 0.5) to classify a transaction as fraudulent
threshold = 0.5
predicted_fraudulent = fraud_probabilities > threshold
predicted_fraudulent

array([False,  True, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True])